# Generated by Django 5.2.3 on 2025-09-29 09:46

import apps.slider.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to=apps.slider.models.upload_slider_image)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تصویر اسلایدر',
                'verbose_name_plural': 'تصاویر اسلایدرها',
            },
        ),
    ]
