# Generated by Django 5.2.6 on 2025-09-24 10:11

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان شغلی')),
                ('description', models.TextField(verbose_name='توضیحات درباره من')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=apps.main.models.upload_to_about, verbose_name='عکس پروفایل')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'درباره من',
                'verbose_name_plural': 'درباره من',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('content', models.TextField(verbose_name='متن مقاله')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.main.models.upload_to_blog, verbose_name='عکس مقاله')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('published', models.BooleanField(default=True, verbose_name='منتشر شده؟')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فرستنده')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل فرستنده')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع پیام')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('read', models.BooleanField(default=False, verbose_name='خوانده شده؟')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام')),
                ('linkdin', models.URLField(blank=True, null=True, verbose_name='لینک لینکدین')),
                ('github', models.URLField(blank=True, null=True, verbose_name='لینک گیت هاب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.main.models.upload_to_main, verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'صفحه اصلی ',
                'verbose_name_plural': 'صفحه های اصلی',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.main.models.upload_to_projects, verbose_name='عکس پروژه')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک پروژه')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته\u200cبندی پروژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نمونه\u200cکار',
                'verbose_name_plural': 'نمونه\u200cکارها',
            },
        ),
    ]
