# Generated by Django 5.2.3 on 2025-10-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'تعداد بازدید',
                'verbose_name_plural': 'تعداد بازدیدها',
            },
        ),
    ]
